### ISSUE TITLE
Inconsistent rule evaluation 

### ISSUE THREAD

**Issue by grzesuav** [open-policy-agent/conftest#364]
Hi, I have following rule :

```yaml

package main

name = input.metadata.name

ingress_prefix = "ingress.kubernetes.io/"

annotations = [key | input.metadata.annotations[key]]

is_there(x) {
  some y
  con := concat(".", ["nginx", x])
  trace(sprintf("%s", [con]))
  con == annotations[y]
}

warn_on_missing_nginx_annotation[msg] {
  input.kind = "Ingress"

  input.metadata.annotations

  count(annotations) != 0

  old_ingress := [annotations[x] | startswith(annotations[x], ingress_prefix)]

  count(old_ingress) != 0

  old_ingress_without_matching_nginx := [old_ingress[x] | not is_there(annotations[x])]

  count(old_ingress_without_matching_nginx) > 0

  msg = sprintf("%s :: Found '%s' annotation without matching 'nginx.*' one : '%s;", [name, ingress_prefix, old_ingress_without_matching_nginx])
}

```

it suppose to find annotation in form `ingress.kubernetes.io/` which does not have matching `nginx.ingress.kubernetes.io/`

Example ingress.yaml :
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test
  namespace: test
  annotations:
    "ingress.kubernetes.io/ssl-redirect": "true"
    "ingress.kubernetes.io/affinity": "cookie"
    "ingress.kubernetes.io/session-cookie-name": "route"
    "ingress.kubernetes.io/session-cookie-hash": "sha1"
    "nginx.ingress.kubernetes.io/ssl-redirect": "true"
    "nginx.ingress.kubernetes.io/affinity": "cookie"
    "nginx.ingress.kubernetes.io/session-cookie-name": "route"
    "nginx.ingress.kubernetes.io/session-cookie-hash": "sha1"
    "nginx.ingress.kubernetes.io/server-snippet": |
      location = /metrics {
        deny all;
      }
    "ingress.kubernetes.io/server-snippet": |
      location = /metrics {
        deny all;
      }
spec:
  rules:
  - host: test
    http:
      paths:
      - path: /
        backend:
          serviceName: test
          servicePort: test
  tls:
  - hosts:
    - test


```

running conftest gives different results :
```
./conftest --version                                                                                                                                   
Version: 0.20.0
Commit: 8415206
Date: 2020-07-16T13:35:34Z

```

like :
* 
```
./conftest test -p ./assets/tests ingress.yaml                                                                                                           ✔  09:58:36 
WARN - ingress.yaml - test :: Found 'ingress.kubernetes.io/' annotation without matching 'nginx.*' one : '["ingress.kubernetes.io/ssl-redirect", "ingress.kubernetes.io/session-cookie-name", "ingress.kubernetes.io/server-snippet", "ingress.kubernetes.io/session-cookie-hash"];
```

* 
```
 ./conftest test -p ./assets/tests ingress.yaml                                                                                                           ✔  09:58:35 
WARN - ingress.yaml - test :: Found 'ingress.kubernetes.io/' annotation without matching 'nginx.*' one : '["ingress.kubernetes.io/session-cookie-hash", "ingress.kubernetes.io/session-cookie-name"];

```
