### ISSUE TITLE
Exception is outputting "No policies found" instead of registering an exception

### ISSUE THREAD

**Issue by 06kellyjac** [open-policy-agent/conftest#412]
Using the example for exceptions: https://www.conftest.dev/exceptions/

```rego
package main

deny_run_as_root[msg] {
  input.kind == "Deployment"
  not input.spec.template.spec.securityContext.runAsNonRoot

  msg := "Containers must not run as root"
}

exception[rules] {
  input.kind == "Deployment"
  input.metadata.name == "can-run-as-root"

  rules := ["run_as_root"]
}
```

This yaml results in a "no policies found" message instead of an exception (as I've seen work correctly before).
With a name different to "can-run-as-root" it fails the policy as expected.

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: can-run-as-root
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
```
