### ISSUE TITLE
privileged container policy for kubernetes passing when it shouldn't

### ISSUE THREAD

**Issue by anandg112** [open-policy-agent/conftest#442]
I am running the following policy for a pod to disallow privileged container but test still passes

command that I run - ` conftest test pod.yaml --all-namespaces`
and output `1 test, 1 passed, 0 warnings, 0 failures, 0 exceptions`

The test should fail as pod is running a privileged container

```
package k8spspprivileged

violation[{"msg": msg}] {
    input.kind == "Pod"
    container := input.spec.template.spec.containers[_]
    not container.securityContext.privileged == false
    msg = "Privileged container is not allowed"
}
```

```
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    created-by: security
spec:
  containers:
  - name: nginx
    image: nginx
    securityContext:
      privileged: true
```
