### ISSUE TITLE
--trace does not work with 0.22.0 when passing multiple yamls

### ISSUE THREAD

**Issue by szymonpk** [open-policy-agent/conftest#454]
As in the title, `--trace` does not work when I pass a YAML with multiple files separated with `---`. It is working fine with the previous version `0.21.0`. If it is intended, sorry for the report.

Test case:

```
---
# Source: base-app/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: RELEASE-NAME-base-app
  labels:
    helm.sh/chart: base-app-0.1.0
    app.kubernetes.io/name: base-app
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "0.0.0"
    app.kubernetes.io/managed-by: Helm
---
# Source: base-app/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: RELEASE-NAME-base-app
  labels:
    helm.sh/chart: base-app-0.1.0
    app.kubernetes.io/name: base-app
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "0.0.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: base-app
    app.kubernetes.io/instance: RELEASE-NAME
```

My policy:

```
package main

deny[msg] {
  input.kind == "Deployment"
  not input.spec.template.spec.securityContext.runAsNonRoot

  msg := "Containers must not run as root"
}

deny[msg] {
  input.kind == "Deployment"
  not input.spec.selector.matchLabels.app

  msg := "Containers must provide app label for pod selectors"
}
```

`0.22.0` run

```
$ conftest test --trace foo.yaml
$
```

`0.21.0` run

```
$ conftest test --trace foo.yaml 
PASS - foo.yaml - 
TRAC - foo.yaml - Enter data.main.deny = _
TRAC - foo.yaml - | Eval data.main.deny = _
TRAC - foo.yaml - | Index data.main.deny = _ matched 0 rules)
TRAC - foo.yaml - | Exit data.main.deny = _
TRAC - foo.yaml - Redo data.main.deny = _
TRAC - foo.yaml - | Redo data.main.deny = _
PASS - foo.yaml - 
TRAC - foo.yaml - Enter data.main.deny = _
TRAC - foo.yaml - | Eval data.main.deny = _
TRAC - foo.yaml - | Index data.main.deny = _ matched 0 rules)
TRAC - foo.yaml - | Exit data.main.deny = _
TRAC - foo.yaml - Redo data.main.deny = _
TRAC - foo.yaml - | Redo data.main.deny = _
```
`0.22.0` works fine if split YAMLs into separate files.
