### ISSUE TITLE
Conftest failed to get readiness probe input in K8s Yaml

### ISSUE THREAD

**Issue by divyha** [open-policy-agent/conftest#496]
```
package main

deny[msg] {
  input.kind == "Deployment"
  containers:=input.spec.template.spec.containers[_]
  readinessProbe:= containers[_].readinessProbe.httpGet.port
  not readinessProbe
  msg:= sprintf("Deployment must have readiness probe")
}

```
Expectations: "Policy should. check whether Deployment has Readiness probe or not."

Actions taken other than above rego file:
tried with input.spec.template.spec.containers[_].readinessProbe

readinessProbe has an object instead of direct value tried it with nested value.

Please let me know am i doing something wrong.

Sample deployment.yaml
```
-------
apiVersion: apps/v1
kind: Deployment
metadata:
   name: app
spec:
 template:
   spec:
    containers:
    - image: [ImageName]
       readinessProbe:
          httpGet:
            path: /api
            port: 8080
```

Note: Removed sensitive values from YAML.
![image](https://user-images.githubusercontent.com/41743573/109717564-a872d500-7bbf-11eb-92fd-de0718fafe8c.png)
