### ISSUE TITLE
The --policy directory and Kubernetes ConfigMaps

### ISSUE THREAD

**Issue by danielpacak** [open-policy-agent/conftest#497]
I was trying to run Conftest as a K8s Job with the official Docker image openpolicyagent/conftest:v0.23.0 and two Volumes of type configMap to provide policy scripts and the configuration file. However, I ended up with a similar error reported in https://github.com/open-policy-agent/opa/issues/782

*Is it possible in Conftest to disable traversing hidden directories within the policy directory? Otherwise Conftest fails with "multiple default rules named found" errors in K8s.*

### Steps to reproduce
1. Create test directory structure:
   ```
   mkdir -p ~/tmp/unboxing/conftest/policy
   cd ~/tmp/unboxing/conftest
   ```
2. Create a sample config file:
   ```
   kubectl create deploy nginx \
     --image nginx \
     -o yaml \
     --dry-run=client > ~/tmp/unboxing/conftest/nginx.deploy.yaml
   ```
3. Download sample policies:
   ```
   wget -O ~/tmp/unboxing/conftest/policy/kubernetes.rego \
     https://raw.githubusercontent.com/aquasecurity/appshield/master/kubernetes/lib/kubernetes.rego
   wget -O ~/tmp/unboxing/conftest/policy/uses_image_tag_latest.rego \
     https://raw.githubusercontent.com/aquasecurity/appshield/master/kubernetes/policies/general/uses_image_tag_latest.rego
   wget -O ~/tmp/unboxing/conftest/policy/file_system_not_read_only.rego \
     https://raw.githubusercontent.com/aquasecurity/appshield/master/kubernetes/policies/general/file_system_not_read_only.rego
   ```
   >  **NOTE** I believe that you can reproduce the same problem with any Rego scripts. To make sure that the scripts used in my test are okey I run Conftest as a Docker container:
   > ```console
   > $ docker run --rm -v $(pwd):/project openpolicyagent/conftest:v0.23.0 test -o json nginx.deploy.yaml
   > [
   > 	{
   > 		"filename": "nginx.deploy.yaml",
   > 		"namespace": "main",
   > 		"successes": 0,
   > 		"failures": [
   > 			{
   > 				"msg": "container nginx of deployment nginx in default namespace should set securityContext.readOnlyRootFilesystem to true"
   > 			},
   > 			{
   > 				"msg": "container nginx of deployment nginx in default namespace should specify image tag"
   > 			}
   > 		]
   > 	}
   > ]
   > ```
4. Create the `policies` ConfigMap with the sample policies:
   ```
   kubectl create configmap policies \
     --from-file policy/kubernetes.rego \
     --from-file policy/uses_image_tag_latest.rego \
     --from-file policy/file_system_not_read_only.rego \
   ```
2. Create the `config-file` ConfigMap with a config file to check:
   ```
   kubectl create configmap config-files \
     --from-file nginx.deploy.yaml \
   ```
3. Create the `conftest` K8s Job:
   ```
   cat << EOF | kubectl apply -f -
   apiVersion: batch/v1
   kind: Job
   metadata:
     creationTimestamp: null
     name: conftest
   spec:
     backoffLimit: 0
     template:
       metadata:
         creationTimestamp: null
       spec:
         volumes:
         - name: policies
           configMap:
             name: policies
         - name: config-files
           configMap:
             name: config-files
         containers:
         - name: conftest
           image: openpolicyagent/conftest:v0.23.0
           volumeMounts:
           - name: policies
             mountPath: /project/policy
             readOnly: true
           - name: config-files
             mountPath: /project
             readOnly: true
           command:
           - conftest
           args:
           - test
           - --trace
           - --output
           - json
           - /project/nginx.deploy.yaml
         restartPolicy: Never
   EOF
   ```
4. Get the logs and see that the `conftest` Job has failed:
   ```console
   $ kubectl logs job/conftest
   Error: running test: load: loading policies: get compiler: 5 errors occurred:
   policy/..2021_03_02_21_47_24.860427643/uses_image_tag_latest.rego:12: rego_type_error: multiple default rules named checkUsingLatestTag found
   policy/..2021_03_02_21_47_24.860427643/file_system_not_read_only.rego:12: rego_type_error: multiple default rules named failReadOnlyRootFilesystem found
   policy/..data/kubernetes.rego:3: rego_type_error: multiple default rules named is_gatekeeper found
   policy/..data/kubernetes.rego:39: rego_type_error: multiple default rules named is_controller found
   policy/..data/kubernetes.rego:29: rego_type_error: multiple default rules named namespace found
   ```
5. Exec to the `conftest` container and list files and directories under the `policy` directory:
   ```console
   $ ls -al /project/policy
   drwxrwxrwx    3 root     root          4096 Mar  2 21:21 .
   drwxrwxrwx    4 root     root          4096 Mar  2 21:21 ..
   drwxr-xr-x    2 root     root          4096 Mar  2 21:21 ..2021_03_02_21_21_44.713983826
   lrwxrwxrwx    1 root     root            31 Mar  2 21:21 ..data -> ..2021_03_02_21_21_44.713983826
   lrwxrwxrwx    1 root     root            37 Mar  2 21:21 file_system_not_read_only.rego -> ..data/file_system_not_read_only.rego
   lrwxrwxrwx    1 root     root            22 Mar  2 21:21 kubernetes.rego -> ..data/kubernetes.rego
   lrwxrwxrwx    1 root     root            33 Mar  2 21:21 uses_image_tag_latest.rego -> ..data/uses_image_tag_latest.rego
   ```
